### PR TITLE
Renaming the project

### PR DESCRIPTION
**Pull request by jpodivin**

### CODE REVIEW

**Comment by FrostyX** [comment]
+1 for the name change but we should probably decide whether `logdetective` or `log-detective` and be consistent about it.

**Comment by TomasTomecek** [comment]
> +1 for the name change but we should probably decide whether `logdetective` or `log-detective` and be consistent about it.

Agreed! So far we have mostly marketed the project as "Log Detective" so I think we can still decide. The website is available under both names.

**Review by xsuchy — APPROVED** [review]
+1 to PR
+1 to "logdetective" as the name of cli tool.

**Comment by jpodivin** [comment]
I think that we should have the same name as is the CLI invocation. And since `logdetective` is lot easier to write than `log-detective` I'm voting for that.

**Review by TomasTomecek — APPROVED** [review]
okay, let's keep logdetective then :)

**Pull request merged**
